services:
#Gateways
  checkbook.gateway.rest:
    class: Beyerz\CheckBookIOBundle\Gateway\RestGateway
    arguments: ["@checkbook.client"]
    calls:
      - [setContainer,['@service_container']]
    public: false

  checkbook.gateway.charge:
    class: Beyerz\CheckBookIOBundle\Gateway\ChargeGateway
    arguments: ["@checkbook.client"]
    calls:
      - [setContainer,['@service_container']]
    public: false

  checkbook.gateway.url_encoded:
    class: Beyerz\CheckBookIOBundle\Gateway\UrlEncodedGateway
    arguments: ["@checkbook.client"]
    calls:
      - [setContainer,['@service_container']]
    public: false

#Models
  checkbook.check:
    class: Beyerz\CheckBookIOBundle\Model\Check\Check
    arguments: ["@checkbook.gateway.rest"]
    public: false

  checkbook.invoice:
    class: Beyerz\CheckBookIOBundle\Model\Invoice\Invoice
    arguments: ["@checkbook.gateway.rest"]
    public: false

  checkbook.subscription:
    class: Beyerz\CheckBookIOBundle\Model\Subscription\Subscription
    arguments: ["@checkbook.gateway.rest"]
    public: false

  checkbook.charge:
    class: Beyerz\CheckBookIOBundle\Model\Charge\Charge
    arguments: ["@checkbook.gateway.charge"]
    public: false

  checkbook.oauth:
    class: Beyerz\CheckBookIOBundle\Model\Oauth\Oauth
    arguments:
      - "@checkbook.gateway.url_encoded"
      - "@checkbook.check"
      - "@checkbook.invoice"
      - "@checkbook.subscription"

    public: false

  checkbook.model:
    class: Beyerz\CheckBookIOBundle\Model\CheckbookIO
    arguments:
      - "@checkbook.check"
      - "@checkbook.invoice"
      - "@checkbook.subscription"
      - "@checkbook.charge"
      - "@checkbook.oauth"

#Twig Extensions
  #Twig extension for embedded check
  twig.embeddedcheck_extension:
    class: Beyerz\CheckBookIOBundle\Twig\Extensions\EmbeddedCheckExtension
    arguments:
      - "%beyerz.checkbook.public_key%"
      - "%beyerz.checkbook.merchant_name%"
      - "%beyerz.checkbook.sandbox%"
    public: false
    tags:
        - { name: twig.extension }