language: php

php:
  - 5.5
  - 5.6
  - 7.0

env:
  - SYMFONY_VERSION=2.8.*
  - SYMFONY_VERSION=dev-master

before_script:
  - echo "memory_limit=1024M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer require symfony/http-foundation:${SYMFONY_VERSION}
  - composer update -o

script: phpunit --coverage-text

notifications:
  email:
    - bailz777+checkbookbundle@gmail.com