language: php

php:
  - 5.5
  - 5.6
  - 7.0

env:
  - SYMFONY_VERSION=2.8.*
  - SYMFONY_VERSION=3.1.*
  - SYMFONY_VERSION=3.2.*

before_script:
  - echo "memory_limit=1024M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer require symfony/symfony:${SYMFONY_VERSION}

script: vendor/bin/simple-phpunit --coverage-text

notifications:
  email:
    - bailz777+checkbookbundle@gmail.com
addons:
  code_climate:
    repo_token: 5d6e9c95da72cf3c6942a61031627f67fcf47d1f28400181f61d5bb9ec82b49e
